carta/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from cookery.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    #cookery
    path('', include('cookery.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cookery/models.py
import hashlib
import os
from datetime import datetime
from pathlib import Path

from crum import get_current_user
from django.contrib.auth.models import User
import qrcode
from django.contrib.sessions.models import Session
from django.db import models
from ckeditor.fields import RichTextField
from colorfield.fields import ColorField
import shutil

from django.shortcuts import get_object_or_404

from .get_user import current_request

# defs
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from docutils.utils.math.latex2mathml import mo


def hash_string(string):
    return hashlib.sha256(string.encode('utf-8')).hexdigest()


def walk_up_folder(path, depth=1):
    _cur_depth = 1
    while _cur_depth < depth:
        path = os.path.dirname(path)
        _cur_depth += 1
    return path


# Create your models here.
class ConfiguracionGodlango(models.Model):
    url = models.CharField(max_length=500)

    def __str__(self):
        return 'Configuraciones de ámbito global'

    class Meta:
        verbose_name_plural = '*  Configuraciones de ámbito global'
        verbose_name = 'Configuración de ámbito global'
        app_label = 'godjango'


class Categoria(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    categoria = models.CharField(max_length=255)
    orden = models.IntegerField()

    def __str__(self):
        return self.categoria

    class Meta:
        verbose_name_plural = '02 - Categorías'
        verbose_name = 'Categoria'
        ordering = ('orden',)


class Configuracion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255, verbose_name='Nombre del negocio')
    logo = models.ImageField(upload_to='cfg/', verbose_name='Imagen principal')
    moneda = models.CharField(max_length=255, verbose_name='Moneda a usar en la plataforma', default='U.S.D')
    color = ColorField(default='#97824B', verbose_name='Color principal')
    color2 = ColorField(default='#005238', verbose_name='Color secundario')
    color3 = ColorField(default='#005238', verbose_name='Color de fondo')
    tel = models.CharField(max_length=255, verbose_name='Telefono fijo del establecimiento', help_text='Opcional',
                           blank=True)
    direccion = models.CharField(max_length=255, verbose_name='Dirección particular', help_text='Opcional', blank=True)
    whatsapp = models.CharField(max_length=255, verbose_name='Contacto de WhatsApp', help_text='Opcional', blank=True)
    recibir_pedidos = models.BooleanField(default=True)
    qr_img = models.CharField(max_length=900)

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="300" height="300" />' % (str(self.qr_img)))

    image_tag.short_description = 'Vista previa'

    def show_url(self):
        return mark_safe("<a href='/media/%s'>%s</a>" % (
        self.qr_img, str(ConfiguracionGodlango.objects.all()[0].url) + str(self.usuario.username)))

    show_url.short_description = 'Url'

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        if not self.qr_img:
            user = self.usuario
            qr = qrcode.make()
            qr = qrcode.QRCode(
                version=1,
                error_correction=qrcode.constants.ERROR_CORRECT_H,
                box_size=50,
                border=4,
            )
            qr.add_data(str(ConfiguracionGodlango.objects.all()[0].url + str(user.username)))
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white").convert('RGB')
            self.qr_img = "/qr/" + str(self.pk) + '.png'
            # qr.save("media/qr/" + str(self.id) + '.png')
            img.save("media/qr/" + str(self.pk) + '.png')
            self.regenerar = False
        super(Configuracion, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = '01 - Configuraciones'
        verbose_name = 'Configuración'


class Product(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)
    cfg = models.ForeignKey(Configuracion, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='productos/', verbose_name='Imagen', help_text='Resolución recomendada 400x300')
    name = models.CharField(max_length=255, verbose_name='Nombre')
    price = models.FloatField(default=0, verbose_name='Precio', help_text='Opcional')
    contenido = RichTextField(verbose_name='Descripción', null=True, blank=True)
    visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def __init__(self, *args, **kwargs):
        super(Product, self).__init__(*args, **kwargs)
        if not self.cfg:
            # session = Session.objects.all()
            user = get_current_user()
            # for item in session:
            #     if item.get_decoded().get('_auth_user_id') != None:
            #         user = User.objects.get(pk=item.get_decoded().get('_auth_user_id'))
            try:
                cfg = get_object_or_404(Configuracion, usuario=user)
            except:
                return
            self.cfg = cfg
        self.__precio = self.price

    def resumen(self):
        if len(self.contenido) > 60:
            return self.contenido[:57] + ' ...'
        return self.contenido

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="120" height="120" />' % (str(self.image)))

    image_tag.short_description = 'Vista previa'

    class Meta:
        verbose_name_plural = 'Productos'
        verbose_name = 'Producto'


class Zona(models.Model):
    cfg = models.ForeignKey(Configuracion, on_delete=models.CASCADE)
    dia = models.CharField(max_length=255)
    horario = models.CharField(max_length=255)

    def __str__(self):
        return 'Especificaciones del servicio a domicilio'

    class Meta:
        verbose_name = 'Especificaciones del servicio a domicilio'
        verbose_name_plural = 'Especificaciones del servicio a domicilio'

templates/aa.html
<!--A Design by W3layouts 
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Cookery A Food Category Flat Bootstrap Responsive Website Template | Single :: w3layouts</title>
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Cookery Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!---->
<link href='//fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
<link href="css/styles.css" rel="stylesheet">
<!-- animation-effect -->
<link href="css/animate.min.css" rel="stylesheet"> 
<script src="js/wow.min.js"></script>
<script>
 new WOW().init();
</script>
<!-- //animation-effect -->

</head>
<body>
<div class="header head">
	<div class="container">
		<div class="logo animated wow pulse" data-wow-duration="1000ms" data-wow-delay="500ms">
			<h1><a href="index.html"><span>C</span><img src="images/oo.png" alt=""><img src="images/oo.png" alt="">kery</a></h1>
		</div>
		<div class="nav-icon">		
			<a href="#" class="navicon"></a>
				<div class="toggle">
					<ul class="toggle-menu">
						<li><a  href="index.html">Home</a></li>
						<li><a  href="menu.html">Menu</a></li>
						<li><a   href="blog.html">Blog</a></li>
						<li><a  href="typo.html">Codes</a></li>
						<li><a  href="events.html">Events</a></li>
						<li><a  href="contact.html">Contact</a></li>
					</ul>
				</div>
			<script>
			$('.navicon').on('click', function (e) {
			  e.preventDefault();
			  $(this).toggleClass('navicon--active');
			  $('.toggle').toggleClass('toggle--active');
			});
			</script>
		</div>
	<div class="clearfix"></div>
	</div>
	<!-- start search-->	
		
</div>
<!--content-->
<div class="blog">
	<div class="container">
		
		<div class="col-md-9 ">
		<!--content-->
<div class="single">
	
		<div class="single-top">
			<img class="img-responsive wow fadeInUp animated" data-wow-delay=".5s" src="images/ss.jpg" alt="" />
				<div class="lone-line">
					<h4>Social Sense Perception of Loneliness</h4>
						<ul class="grid-blog">
							<li><span><i class="glyphicon glyphicon-time"> </i>08.09.2014</span></li>
							<li><a href="#"><i class="glyphicon glyphicon-comment"> </i>5 Comment</a></li>
							<li><a href="#"><i class="glyphicon glyphicon-share"> </i>Share</a></li>
						</ul>
						<p class="wow fadeInLeft animated" data-wow-delay=".5s">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error.
						<span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
						Lorem ipsum dolor sit amet, consectetur adipisicing elit.</span></p>
				</div>
		</div>
		<div class="comment">
							<h3>Comments</h3>
							 <div class="media wow fadeInLeft animated" data-wow-delay=".5s">
								<div class="code-in">
									<p class="smith"><a href="#">Andey</a> <span>02 June 2014, 15:20</span></p>
									<p class="reply"><a href="#"><i class="glyphicon glyphicon-repeat"> </i>REPLY</a></p>
									<div class="clearfix"> </div>
								</div>
							    <div class="media-left">
							        <a href="#">
							        	<img src="images/si1.jpg" alt="">
							        </a>
							     </div>
							    <div class="media-body">
		
									<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
							      </div>
							    </div>
							    <div class="media media-1 wow fadeInUp animated" data-wow-delay=".5s">
								<div class="code-in">
									<p class="smith"><a href="#"> Rackham</a> <span>02 June 2014, 15:20</span></p>
									<p class="reply"><a href="#"><i class="glyphicon glyphicon-repeat"> </i>REPLY</a></p>
									<div class="clearfix"> </div>
								</div>
							    <div class="media-left">
							        <a href="#">
							        	<img src="images/si.jpg" alt="">
							        </a>
							     </div>
							    <div class="media-body">
		
									<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
							      </div>
							    </div>
								<div class="media wow fadeInRight animated" data-wow-delay=".5s">
								<div class="code-in">
									<p class="smith"><a href="#">Clara</a> <span>02 June 2014, 15:20</span></p>
									<p class="reply"><a href="#"><i class="glyphicon glyphicon-repeat"> </i>REPLY</a></p>
									<div class="clearfix"> </div>
								</div>
							    <div class="media-left">
							        <a href="#">
							        	<img src="images/si2.jpg" alt="">
							        </a>
							     </div>
							    <div class="media-body">
		
									<p>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.</p>
							      </div>
							    </div>
						 </div>
		<div class="leave">
			<h3>Leave a comment</h3>
				<form>
					<div class="single-grid wow fadeInLeft animated" data-wow-delay=".5s">
						
							<input type="text" value="Name" onfocus="this.value='';" onblur="if (this.value == '') {this.value = 'Name';}">
						
							<input type="text" value="E-mail" onfocus="this.value='';" onblur="if (this.value == '') {this.value = 'E-mail';}">
						
						
							<input type="text" value="Web site" onfocus="this.value='';" onblur="if (this.value == '') {this.value = 'Web site';}">
						
							<textarea value=" " onfocus="this.value='';" onblur="if (this.value == '') {this.value = 'Comment';}">Comment</textarea>
						<label class="hvr-rectangle-out">
								<input type="submit" value="Send">
						</label>						
				</div>
				</form>
			</div>
		
</div>
<!---->
<!--//content-->

		</div>
		<div class="col-md-3 categories-grid">
			<div class="search-in animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
				<h4>Search</h4>
					<div class="search">
					<form>
						<input type="text" placeholder="Search" required="" >
						<input type="submit" value="" >
					</form>
					</div>
			</div>
				<div class="grid-categories animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h4>Categories</h4>
					<ul class="popular">
						<li><a href="#"><i class="glyphicon glyphicon-menu-right"> </i>Breakfast</a></li>
						<li><a href="#"><i class="glyphicon glyphicon-menu-right"> </i>Lunch</a></li>
						<li><a href="#"><i class="glyphicon glyphicon-menu-right"> </i>Dinner</a></li>
						<li><a href="#"><i class="glyphicon glyphicon-menu-right"> </i>Dessert</a></li>
						
					</ul>
				</div>
				<div class="blog-bottom animated wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
						<h4>Recent Posts</h4>
							<div class="product-go">
								<a href="single.html" class="fashion"><img class="img-responsive " src="images/bo.jpg" alt=""></a>
								<div class="grid-product">
									<a href="single.html" class="elit">Consectetuer adipiscing</a>
									<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit</p>
								</div>
							<div class="clearfix"> </div>
							</div>
							<div class="product-go">
								<a href="single.html" class="fashion"><img class="img-responsive " src="images/bo1.jpg" alt=""></a>
								<div class="grid-product">
									<a href="single.html" class="elit">Consectetuer adipiscing</a>
									<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit</p>
								</div>
							<div class="clearfix"> </div>
							</div>
							<div class="product-go">
								<a href="single.html" class="fashion"><img class="img-responsive " src="images/bo2.jpg" alt=""></a>
								<div class="grid-product">
									<a href="single.html" class="elit">Consectetuer adipiscing</a>
									<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit</p>
								</div>
							<div class="clearfix"> </div>
							</div>
						</div>

			</div>
<div class="clearfix"> </div>
	</div>
</div>
<!--//content-->
<!--footer-->
	<div class="footer">
		<div class="container">
			<div class="footer-head">
				<div class="col-md-8 footer-top animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
					<ul class=" in">
						<li><a href="index.html">Home</a></li>
						<li><a  href="menu.html">Menu</a></li>
						<li><a  href="blog.html">Blog</a></li>
						<li><a  href="events.html">Events</a></li>
						<li><a  href="contact.html">Contact</a></li>
					</ul>					
						<span>There are many variations of passages</span>
				</div>
				<div class="col-md-4 footer-bottom  animated wow fadeInLeft" data-wow-duration="1000ms" data-wow-delay="500ms">
					<h2>Follow Us</h2>
					<label><i class="glyphicon glyphicon-menu-up"></i></label>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis.</p>
					<ul class="social-ic">
						<li><a href="#"><i></i></a></li>
						<li><a href="#"><i class="ic"></i></a></li>
						<li><a href="#"><i class="ic1"></i></a></li>
						<li><a href="#"><i class="ic2"></i></a></li>
						<li><a href="#"><i class="ic3"></i></a></li>
					</ul>

				</div>
			<div class="clearfix"> </div>
					
			</div>
			<p class="footer-class animated wow bounce" data-wow-duration="1000ms" data-wow-delay="500ms">&copy; 2016 Cookery . All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
		</div>
	</div>		
	<!--//footer-->

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ cfg.nombre }} - {% block titulo %}{% endblock %}</title>
    <link href="{% static 'cookery/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <script src="{% static 'cookery/js/jquery.min.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Cookery Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <link href='//fonts.googleapis.com/css?family=Raleway:400,200,100,300,500,600,700,800,900' rel='stylesheet'
          type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet'
          type='text/css'>
    <script type="text/javascript" src="{% static 'cookery/js/move-top.js' %}"></script>
    <script type="text/javascript" src="{% static 'cookery/js/easing.js' %}"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);
            });
        });
    </script>
    <link href="{% static 'cookery/css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'cookery/css/component.css' %}"/>
    <link href="{% static 'cookery/css/animate.min.css' %}" rel="stylesheet">
    <script src="{% static 'cookery/js/wow.min.js' %}"></script>
    <script>
        new WOW().init();
    </script>
    {% block estilo-1 %}{% endblock %}
    <link href="{% static 'cookery/css/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
    {% block estilo-2 %}{% endblock %}
    <link href="{% static 'cookery/css/custom.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <style>
        .feedback {
            background-color: {{ cfg.color2 }};
            border-color: {{ cfg.color2 }};
            padding: 15px 20px;
        }

        .navicon {
            z-index: 9999;
        }

        .blockDiv {
            position: absolute;
            top: 0px;
            left: 0px;
            background-color: #FFF;
            width: 0px;
            height: 0px;
            z-index: 998;
        }
    </style>
</head>
<body>
{% block header %}{% endblock %}
<a id="button"></a>
<div id="mybutton">
    <button {% if cfg.recibir_pedidos == True %}onclick="window.location.replace('/{{ cfg.usuario.username }}/contacto/');"{% endif %} class="feedback"><img
            class="" {% if cfg.recibir_pedidos == True %}src="{% static 'cookery/images/whatsapp.png' %}"{% else %}style="width: 35px" src="{% static 'cookery/images/no_whatsapp.png' %}"{% endif %}><br>
        <label id="total_ajax">{{ total }}</label> {{ cfg.moneda }}
    </button>
</div>
<div id="message" class="is-hidden"></div>
{% block contenido %}{% endblock %}
<div class="footer">
    <div class="container">
        <div class="footer-head">
            <div class="col-md-8 footer-top animated wow fadeInRight" data-wow-duration="1000ms" data-wow-delay="500ms">
                <span style="margin-top: 0;">{{ cfg.direccion }}
                </span>
                <span style="margin-top: 0; border-top-color: transparent">
                    {% for item in cfg.zona_set.all%}
                        • {{ item.dia }}  {{ item.horario }} <br>
                    {% endfor %}
                </span>
            </div>

            <div class="col-md-4 footer-bottom  animated wow fadeInLeft" data-wow-duration="1000ms"
                 data-wow-delay="500ms">
                <h2>{{ cfg.tel }}</h2>
                <label><i class="glyphicon glyphicon-menu-up"></i></label>
                <p style="font-size: 25px">{% if cfg.tel %}
                    Teléfono
                {% endif %}
                </p>
            </div>
            <div class="clearfix"></div>

        </div>
        <p class="footer-class animated wow bounce" data-wow-duration="1000ms" data-wow-delay="500ms">&copy;
            2021 {{ cfg.nombre }}. Desarrollado por GoDjango </p>
    </div>
</div>
<script>
    function unblock_screen() {
        $('#screenBlock').animate({opacity: 0}, 200, function () {
            $('#screenBlock').remove();
        });
    }

    function block_screen() {
        console.log('')
        $('<div id="screenBlock"></div>').appendTo('body');
        $('#screenBlock').css({opacity: 0, width: $(document).width(), height: $(document).height()});
        $('#screenBlock').addClass('blockDiv');
        $('#screenBlock').animate({opacity: 0.7}, 200);
    }
</script>
{% block extra-scripts %}{% endblock %}

</body>
</html>

templates/contact.html
<html>
    <head>

    </head>
    <body>
        <h1 style="text-align: center; top: 50%; position: relative; font-family: 'Segoe UI Black'; font-size: 40px">by GoDjango</h1>
    </body>
</html>